// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Home", "        Home                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                                                                                                  Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("1-pagina-principal/estructura/master-page-layoutgrid.html", "Master Frame", "        Master Frame                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                      Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("1-pagina-principal/menu/contatos.html", "Contactos", "        Contactos                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                Contactos                      INFORMACION PARA CONTACTOS      PERSONERIA JURIDICANro 516 - FUN. 18 DE MARZO DE 2001RUC.  80052336-9 TELEFONO 0973  555 746 /  0973 188 562EMAILasefran@outlook.com           LEAVE US A MESSAGE                            Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("2-estructura-copia-de-seguridad/about-us-layoutgrid.html", "About Me", "        About Me                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                About Us                      Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim liber veniam, quis nostrud exerci tation ullamcorper suscipit et lobortis nisl ut aliquip ex ea commodo consequat. Duis is autem vel eum iriure dolor in hendrerit in vulputate velit vel esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui elit blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, praesent consectetuer tation adipiscing elit, sed diam nonummy nibh nobis euismod ea tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation vel ullamcorper suscipit lobortis nisl ut aliquip ex ea duis iusto commodo consequat. Duis autem vel eum iriure dolor in ea hendrerit in vulputate velit esse molestie consequat, vel et illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril nisl delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option congue nihil odio imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer et adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper dolore suscipit eum ipsum lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate et velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan.                            Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("2-estructura-copia-de-seguridad/services-layoutgrid.html", "Photo Album", "        Photo Album                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                Services                                             iOS                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.                                    Android                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.                                    Windows                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.                                    HTML                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.                         Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("2-estructura-copia-de-seguridad/portfolio-layoutgrid.html", "Photo Album", "        Photo Album                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                Portfolio                                                                                                                                                Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("2-estructura-copia-de-seguridad/index-layoutgrid.html", "Home", "        Home                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                                                      June 21, 2018Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim liber veniam, quis nostrud exerci tation ullamcorper suscipit et lobortis nisl ut aliquip ex ea commodo consequat. Duis is autem vel eum iriure dolor in hendrerit in vulputate velit vel esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui elit blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, praesent consectetuer tation adipiscing elit, sed diam nonummy nibh nobis euismod ea tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation vel ullamcorper suscipit lobortis nisl ut aliquip ex ea duis iusto commodo consequat. Duis autem vel eum iriure dolor in ea hendrerit in vulputate velit esse molestie consequat, vel et illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril nisl delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option congue nihil odio imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer et adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper dolore suscipit eum ipsum lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate et velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan.                                                            Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("2-estructura-copia-de-seguridad/master-page-layoutgrid.html", "Master Frame - copia", "        Master Frame - copia                        ASEFRAN              Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Rese&#241 a&nbsp Historica  Vision&nbsp y&nbsp Mision  Organizacion  Noticias  Reglamentos  Actividades  Registro&nbsp para&nbsp Nuevos&nbsp Socios      &nbsp Inicio&nbsp de&nbsp Sesion  &nbsp Contactos                      Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("3-proteccion/iniciosesion.php", "Inicio de Sesion ", "          Inicio de Sesion                             INICIO DE SESION PARA SOCIOS                                Inicie Sesion                                                                                              Registro para Nuevos Socios                   ", "");
   this[database_length++] = new SearchPage("3-proteccion/registrnuevsocios.php", "Registros para Nuevos Socios", "        Registros para Nuevos Socios                      REGISTROS PARA NUEVOS SOCIOS      Para poder tener acceso al interior del sistema se debe formar parte de la ASOCIACION DE ELECTRICISTA DE PRESIDENTE FRANCO - ASEFRAN. En caso de que ya formes parte y solo necesitas tu usuario y contraseña podes enviar un correo al administrador de la pagina para que este ingrese tus datos al sistema.Podes enviar tus datos al correo de la asociacion asefran@outlook.com favor llenar con tu nombre completo telefono y correo.Pagina de Inicio                   ", "");
   this[database_length++] = new SearchPage("3-proteccion/acceso-denegado.php", "Acceso Denegado", "        Acceso Denegado                                         ", "");
   this[database_length++] = new SearchPage("3-proteccion/contrase-invalida.php", "Contraseña Invalida", "        Contraseña Invalida                            CONTRASEÑA O NOMBRE DE USUARIO INVALIDO, INTENTE&nbsp  DE NUEVO                   ", "");
   this[database_length++] = new SearchPage("5-panel-de-socios/master-panel-de-socios.html", "Panel de Socios", "        Panel de Socios                        Bienvenido               Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Organizacion  Noticias  Reglamentos  Actividades        &nbsp Configuracion&nbsp de&nbsp Cuenta  &nbsp Configuracion&nbsp de&nbsp Cuenta      Cambio&nbsp de&nbsp Contrase&#241 a      &nbsp Actas&nbsp de&nbsp Asamblea                      Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("5-panel-de-socios/inde-panel-de-socio.php", "Panel de Socios", "          Panel de Socios                        Bienvenido               Menu&nbsp &nbsp &nbsp       &nbsp Inicio    &nbsp La&nbsp Asefran  &nbsp La&nbsp Asefran      Organizacion  Noticias  Reglamentos  Actividades        &nbsp Configuracion&nbsp de&nbsp Cuenta  &nbsp Configuracion&nbsp de&nbsp Cuenta      Cambio&nbsp de&nbsp Contrase&#241 a      &nbsp Actas&nbsp de&nbsp Asamblea                                                        June 21, 2018Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim liber veniam, quis nostrud exerci tation ullamcorper suscipit et lobortis nisl ut aliquip ex ea commodo consequat. Duis is autem vel eum iriure dolor in hendrerit in vulputate velit vel esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui elit blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, praesent consectetuer tation adipiscing elit, sed diam nonummy nibh nobis euismod ea tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation vel ullamcorper suscipit lobortis nisl ut aliquip ex ea duis iusto commodo consequat. Duis autem vel eum iriure dolor in ea hendrerit in vulputate velit esse molestie consequat, vel et illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril nisl delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option congue nihil odio imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer et adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper dolore suscipit eum ipsum lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate et velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan.                                                            Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("6-actas-de-asamblea/1-panel-actas/master-actas.html", "Panel de Socios", "        Panel de Socios                              Registros de Actas              Menu&nbsp &nbsp &nbsp       &nbsp Inicio  &nbsp Panel&nbsp Principal    &nbsp Actas&nbsp por&nbsp a&#241 o  &nbsp Actas&nbsp por&nbsp a&#241 o      2018                                Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("6-actas-de-asamblea/1-panel-actas/index-actas.php", "Panel de Socios", "          Panel de Socios                              Registros de Actas              Menu&nbsp &nbsp &nbsp       &nbsp Inicio  &nbsp Panel&nbsp Principal    &nbsp Actas&nbsp por&nbsp a&#241 o  &nbsp Actas&nbsp por&nbsp a&#241 o      2018                                                                  June 21, 2018Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim liber veniam, quis nostrud exerci tation ullamcorper suscipit et lobortis nisl ut aliquip ex ea commodo consequat. Duis is autem vel eum iriure dolor in hendrerit in vulputate velit vel esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui elit blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.Lorem ipsum dolor sit amet, praesent consectetuer tation adipiscing elit, sed diam nonummy nibh nobis euismod ea tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation vel ullamcorper suscipit lobortis nisl ut aliquip ex ea duis iusto commodo consequat. Duis autem vel eum iriure dolor in ea hendrerit in vulputate velit esse molestie consequat, vel et illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril nisl delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option congue nihil odio imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer et adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper dolore suscipit eum ipsum lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate et velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan.                                                            Copyright 2018 - www.asefran.com.py         ", "");
   this[database_length++] = new SearchPage("6-actas-de-asamblea/2018/indice-acta-2018.php", "Home", "          Home                              Registros de Actas              Menu&nbsp &nbsp &nbsp       &nbsp Inicio  &nbsp Panel&nbsp Principal    &nbsp Actas&nbsp por&nbsp a&#241 o  &nbsp Actas&nbsp por&nbsp a&#241 o      2018                                                                  Diciembre  25/12/18                                                            Copyright 2018 - www.asefran.com.py         ", "");
   return this;
}
